language: rust
after_success: |
    cargo doc \
    && echo '<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html && \
    sudo pip install ghp-import && \
    ghp-import -n target/doc && \
    git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages









